Cloud bastion
Otus-DevOps-2022-05/MrAxel777_infra pull request #2
Opened 2022-07-01 06:50 UTC by MrAxel777

Task is completed.

2022-07-02 16:09 UTC, mrgreyves requested changes
Здравствуйте!)
У вас где то тесты потерялись =(
Нужно их добавить

2022-07-13 22:04 UTC, MrAxel777 commented
Добрый день!
Какие тесты? уточните. Файлы конфигураций добавлены. Про тесты в методичке ничего не нахожу.

2022-07-14 12:21 UTC, mrgreyves requested changes
Здравствуйте!)
Тесты, должны были быть добавлены еще в дз play-travis
Когда мы настраивали github actions и добавляли workflow с проверками

2022-07-28 11:26 UTC, mrgreyves requested changes
Здравствуйте!)
У вас не хватает workflow
В которых выполняются пайплайны github actions 
Которые в свою очередь проверяют корректность выполнения дз
Нужно их добавить

2022-08-15 07:16 UTC, mrgreyves approved these changes
Здравствуйте!)
Вот теперь все корректно, апрув =)

2022-08-15 17:28 UTC, merged