Play travis
Otus-DevOps-2022-05/MrAxel777_infra pull request #4
Opened 2022-07-15 12:23 UTC by MrAxel777

Added files as requested on page 12 of Методические рекомендации (add template)

2022-07-15 14:09 UTC, mrgreyves requested changes
Здравствуйте!)
В дз нехватает некоторого количества файлов
Нужно добавить github workflow что бы появились тесты
Стоит свериться с методическим указанием
ДЗ возвращаю на доработку

2022-07-15 20:45 UTC, MrAxel777 commented
Workflows are added.

2022-07-15 20:52 UTC, MrAxel777 commented
Workflows are added. I don't know why workflow is failed.

2022-07-16 09:21 UTC, mrgreyves requested changes
Здравствуйте!)
Оставил комментарий к файлу который нужно исправить =)

2022-07-16 09:21 UTC, mrgreyves commented on test.py
> +        self.assertEqual(1 + 1, 1)
Смотрим вот сюда внимательно
Исправляем ошибку =)

2022-07-27 18:28 UTC, MrAxel777 commented
Resolved. 1+1=2

2022-07-27 18:35 UTC, MrAxel777 commented
Errors are resolved in test.py

2022-07-28 11:22 UTC, mrgreyves approved these changes
Здравствуйте!)
Вот теперь дз выполнено корректно
Апрув ^_^

2022-08-06 13:21 UTC, merged